### PR TITLE
More grammar and formatting fixes

### PR DESCRIPTION
**Pull request by MohamedAlFahim**

### CODE REVIEW

**Comment by MohamedAlFahim** [comment]
I think I accidentally reverted my previous fixes by making a second set of fixes.

**Comment by dddomodossola** [comment]
If you want you can add commits to this pull request in order to fix the reverted changes, then I can merge

**Comment by MohamedAlFahim** [comment]
I made a few more fixes at the same time

**Comment by dddomodossola** [comment]
Thank you so much

**Pull request merged**
