### PR TITLE
server: automatically update html when anything changes

### PR DESCRIPTION
**Pull request by nzjrs**
This improves responsiveness dramatically. Please test as
there might be some bugs. Also, maybe performance could be
further improved by moving the event.clear call to another place.

Use an event object to signal a redraw any time a message
is recieved from the client (i.e. any websocket sendCallback
call).

This allows one to remove the update timer / update interval
completely.

Also move to a lock rather than a semaphore, as I think that
is the desired semantics

### CODE REVIEW

**Comment by dddomodossola** [comment]
Today I will test this. Basically the idea seems to be really good.

**Comment by dddomodossola** [comment]
Seems to work perfectly for updates generated by client events. But there is no update for the changes generated by the server. For example, in widgets_overview_app, the Label updated by Timer does not updates the gui until I generate an event. So the timed update should still be necessary.

**Comment by KenT2** [comment]
For the Timer situation could you include a function in Remi that the App can call to update the display.

**Comment by nzjrs** [comment]
Thanks.

There is actually a simple way to remove the timer once I know everywhere
it is called ;-)

**Comment by nzjrs** [comment]
Actually, just checking, what do you mean @dddomodossola 'there is no update for the changes generated by the server'?

Did you set the timeout to a large value and observe no updates? or you observe no updates using the version of the code in this branch?

**Comment by dddomodossola** [comment]
@nzjrs 
Yeah, I increased the update_interval with a large value and no updates append untill the timeout.

**Comment by nzjrs** [comment]
Ok cool. I was worried there was another bug elsewhere.

Did you notice the increased performance / responsiveness? If the branch otherwise works then it can be merged as-is, if you like.

I can remove the update timer later, by setting the event every time self.attributes is touched. @KenT2 I would also add a redraw/refresh() method that redraws the widget

**Comment by dddomodossola** [comment]
@nzjrs Yeah it works very well and it's obvious that the performances get increased, for sure you can merge.

**Comment by nzjrs** [comment]
ok thanks. I'll merge it later tonight.

**Comment by awesomebytes** [comment]
Umm closed without merging? Wasn't this good?

**Comment by nzjrs** [comment]
It was 'merged'.

I rebased and applied it directly to master. No need for a dirty merge ;-)

**Comment by nzjrs** [comment]
@KenT2 I added ```Widget.redraw()``` which will redraw the widget immediately.

**Comment by awesomebytes** [comment]
Oki. I do prefer the "dirty merges", I'm used to follow what happens with that with ease. But that's just a way of working.

Thanks for the improvement!

**Pull request closed without merging**
