### PR TITLE
Allow nested sub-folders for resource loading!

### PR DESCRIPTION
**Pull request by MaxMorais**
This fix allow subfolders in resolution to load static assets, also prevents back navigation into the file system.

### CODE REVIEW

**Comment by dddomodossola** [comment]
@MaxMorais I've made some tests on this, and found some problems.
The regex to match files seems wrong, i.e. it doesn't accept "/res/.test.extension". Maybe we should make it simpler.
The _get_static_file have to be changed to directly point to the file of interest, instead of probing file exists on different paths.
I will make some changes, but however the idea is ok.

**Comment by MaxMorais** [comment]
@dddomodossola, I cannot saw any issue into the regex, I tested into regex101 and sounds okay:

online regex tester and debugger php pcre python golang and javascript

About the fact that `_get_static_file` should directly point to the file of interest I agree with you!
If you want, I can work on that.

Can you give me more details about the issue regarding the pattern issue?

**Comment by dddomodossola** [comment]
@MaxMorais Excuse the delay. The problem with the regex is that it doesn't accept paths like:
**"/res/.myvalidpath."**
this is just an example. I suppose to make that regex simpler, to accept almost all paths that starts with "/res/" and remove ".." by code (i.e. path.replace("..", "") ). This, just to simplify the regex.

For the multiple path definition, you can fix it if you have the time. The problem is this:
- Remi actually accepts **List** of paths;
- When you point to a file with **/res/**, you now must probe all the folders defined in the list;

I propose to:
- Accept **Dictionary** instead of **List**;
- You add paths with a name like: {'images':'/home/myimages/', 'res':'./myresources/'};
- When you would like to point to a file you should do **'/images/image1.png'**;
- Inside remi server, **/images/** gets replaced by the dict value **'/home/myimages/'** and so the path becomes **'/home/myimages/image1.png'**.
It is to say you can have multiple resource folders defined in dictionary, and identified by dictionary key.

**Comment by dddomodossola** [comment]
@MaxMorais look at this https://github.com/dddomodossola/remi/tree/MaxMorais-patch-2 . 
In this version resource folders are defined in a dictionary, like {'my_resources':'/root/test/', 'my_other_resources':'/root/foo/other/'}.
When you want to point to a file you have to do: 'my_resources://myimage.png' and 'my_other_resources://mysound.mp3'
Nested folders are accepted, and so you can do: 'my_resources://subfolder1/another/myimage2.png'

**Pull request merged**
