### PR TITLE
gui: always respect padding

### PR DESCRIPTION
**Pull request by nzjrs**
I think this is what was intended. Otherwise vertical padding was not respected in many cases

comments?

### CODE REVIEW

**Comment by dddomodossola** [comment]
No, this piece of code was done to align the widget's center at the center of the container. If the layout is vertical the margins left and right are calculated as (container.width-widget.width)/2 and the vertical spacing is appliend to top and bottom margins, differently is the layout is horizontal the top and bottom margins are calculated as (container.height-widget.height)/2 and left and right margins are the specified spacing.

**Comment by nzjrs** [comment]
I'll make you a test case that demonstrates this does the wrong thing sometimes. I have patched it out in my code and everything looks more correct.

**Comment by nzjrs** [comment]
And BTW, I think hardcoding these sorts of things on every widget makes it harder to support material and other CSS frameworks....

**Comment by dddomodossola** [comment]
I'm not sure about this but maybe. It is that this piece of code was not implemented thinking at material design implementation.

**Comment by nzjrs** [comment]
It is surprising that running this branch against the demo app results in
it almost looking the same.

**Comment by dddomodossola** [comment]
It is normal, because the containers are sized to fit the content in these examples. But there will be no more alignment with these changes. I think that, until we do not have a material design (that maybe will take care about layouting), we should not merge this.

**Comment by nzjrs** [comment]
Its just seems inefficient to do it this way. If you always respect padding
/ margin then you can -1 size your widgets in a container and they pack
correctly.  Without this patch you have to manually size everything.

**Comment by dddomodossola** [comment]
Ok, I tested the -1 sizing and you are right. So the autosizing gets implemented automatically, this is a good thing! I only dislike that all gets aligned on the left for vertical layuot, and on the top for horizonal, but maybe it will be solved differently later.

**Pull request merged**
