### PR TITLE
Additional Examples

### PR DESCRIPTION
**Pull request by KenT2**
Added checkbox to dialog
Added Timer function
Removed Idle()

### CODE REVIEW

**Comment by dddomodossola** [comment]
Thank you Ken. However the idle function could be useful for operations that have to be done sincronously with the interface update. So should be better to reintegrate also the idle function.

**Comment by KenT2** [comment]
It might be worth changing the comment in the code to something like:

         """ Useful function to schedule tasks that need to be synchronised 
with the interface update; otherwise use a Timer
         Called every UPDATE_INTERVAL """

**Comment by nzjrs** [comment]
wait, @dddomodossola did you merge this commit including the idle removal? was that the aim?

**Comment by dddomodossola** [comment]
@nzjrs 
I committed other changes, and added again the idle function. Maybe this is not the right way to do this, your right.

**Pull request merged**
