### PR TITLE
server: rewrite process_all

### PR DESCRIPTION
**Pull request by nzjrs**
removes a lot of old code related to post handling

I tested this an everything seems to work as before. Could you please also test before merge?

### CODE REVIEW

**Comment by dddomodossola** [comment]
John, the reworked FileDownloader is the case you have to see. His download function returns headers and the required resource to download. I found no better solution.
However I imagine different cases where a widget should be a GET RESOURCE provider.

**Comment by nzjrs** [comment]
It would be helpful if you add an example of the FileDownloader to widgets_overview

**Comment by dddomodossola** [comment]
It's done, on the widgets_overview you can see a link "download". It will call the code we spoken about.

**Comment by cyberpro4** [comment]
That download link should be a button anyway..

**Comment by dddomodossola** [comment]
Yes I know. Now it is feasible with the reworked "download" method.

**Comment by nzjrs** [comment]
I'm confused. The old download method seemed to work. What is the improvements the new one brings?

**Comment by nzjrs** [comment]
I updated process_all to support the new download widget.

**Pull request merged**
