### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by allanderek**
Hello,

I am looking to provide something of a test suite for REMI. This represents just the first initial strategy for testing, but ultimately the plan is to test most of the functionality. If this works well it might also provide a framework for users of the library to test their own applications.

I've updated the README file to include a section on tests which I hope is sufficient for you to try this out yourself (although I'm working on Linux, so if you're on Windows it might be non-trivial).

The testing scheme relies on selenium driving a phantomjs instance. Which does mean we need to install phantomjs. 

In the future it would be best if we didn't need the section in the README and people could run the tests with simply `python setup.py test`. I think that's possible, but for now I just want to understand if you would be interested in me continuing this effort, or if you're not really interested in adding a test-suite, or you have some other means/framework in mind for it.

So I guess, this is mostly a question of what do you think? Should I continue this effort?

### CODE REVIEW

**Comment by dddomodossola** [comment]
@allanderek Thank you a lot for contributing to this project! :-)  I ever wanted a test suite, so my answer is yes, I'm really interested in this. Now I'm abroad, and I will be unable to merge and test this shortly. I will try it as soon as possible.

**Comment by allanderek** [comment]
That's great. There is no rush to merge in, and I'm quite sure that there are some things you might disagree with. However, it's great to just know I can continue this line of work.

**Comment by dddomodossola** [comment]
Merged in branch allanderek_tests

**Comment by khink** [comment]
This was merged into `origin/allanderek-tests`, but why not into the master? What is lacking?

**Comment by nzjrs** [comment]
Probably all the unrelated changes

**Comment by khink** [comment]
@nzjrs Would you (or @dddomodossola) be willing merge this if the issues are resolved?

Why i'm asking: I'm about to spend some time on testing a Remi-based project for a customer, and this seems like the best approach. I'd like to see if i can get it to work. 

This would also require an effort from the Remi maintainers in pointing out in detail what the issues are, so they can be resolved. A merged branch would be the goal.

@allanderek, are you using tests in Remi, and do you maybe have something new to add?

**Comment by allanderek** [comment]
Sorry I haven't used Remi for a while.

**Comment by khink** [comment]
Ok, thanks for the answer!

**Pull request closed without merging**
