### PR TITLE
Editor app

### PR DESCRIPTION
**Pull request by dddomodossola**
Most important changes.
Removed the hardcoded size and layout from the widgets.
Added a facility functions set_size and set_layout_orientation in order to make it ease to set size and layout in case of need.
Fixed Widget.remove_child. Now the child is removed also from _render_children_list.
Created a wysiwyg Editor app. It's incomplete and dirty, but it's a preview.

### CODE REVIEW

**Comment by awesomebytes** [comment]
Looks promising!! Looks like we are going towards version 1.0? :D

**Comment by dddomodossola** [comment]
:-D A lot of work is still pending, but yeah, the library is evolving day by day. Have you tried the editor? Is incomplete, but it is already possible to export a working program!

**Comment by nzjrs** [comment]
there are lots of things I could comment on here. how much and how detailed feedback would you like?

how confident are you rebasing / reordering commits, etc?

**Comment by dddomodossola** [comment]
You can begin with an overview (with low detail level) and we will comment on, going deeply where necessary.

**Comment by nzjrs** [comment]
while I like the layout changes, removing w,h in the constructor just means you must now call set_size() on every widget. Why not just add **kwargs to every widget constructor and pass it to the base class. If width=xx or height=yy are present, then call set_size() in the base class __init__

**Comment by dddomodossola** [comment]
I like this idea. What do you think about doing this more extensively to all style parameters and attributes? I mean a constructor like 
Widget(style={'width':'10px', 'height':'10px'}, attributes={'tabindex':1})

**Comment by nzjrs** [comment]
what do you mean by attributes vs style parameters? I don't see the distinction between the two.

**Comment by awesomebytes** [comment]
I think a dictionary-like parameter in the constructor looks weird to me.

2016-01-21 14:37 GMT+01:00 Davide <notifications@github.com>:

**Comment by dddomodossola** [comment]
Style and attributes are two different dictionaries in the Widget class, and it is convenient to have them separate. So I imagined that assigning them in the constructor could be useful.
However yes, it could appear weird.

**Comment by dddomodossola** [comment]
Now width and height parameters are accepted from all widgets constructors. Furthermore the editor_app height is 100% and fits the window height.

**Comment by nzjrs** [comment]
looks much better. I will take another look tonight

**Comment by dddomodossola** [comment]
Hi John, please take a look at the HorizontalContainer and VerticalContainer. They uses no hardcoded widgets positions to align widgets. The widgets are aligned automatically thanks to css properties.

Furthermore please give me a feedback about the editor_app. It is incomplete for sure but can be a good tech preview. My dream is to show it at euroPython. What do you think about this?
The next step about the editor is the event signal connection. The code is already capable to 'compile' (produce automatically the code) a python program with the signal interconnection, it is only missing the interface with the user.

**Pull request merged**
