### PR TITLE
Tabbed Editor Example and options for GenericDialog buttons

### PR DESCRIPTION
**Pull request by KenT2**
This pull request responds to the following issues:
#100 Confirm should not automatically hide a Generic Dialog 
#84 add_field in Dialogs and append in main pages - App side implementation in tabbed_editor.py
#82 Tabview - App side implementation in tabbed_editor.py
#17 Two Simple dialogs - App side implementation in tabbed_editor.py

### CODE REVIEW

**Comment by nzjrs** [comment]
there are a lot of unneeded merge commits here. can you re-submit this pull request as a clean commit series on top of HEAD?

**Comment by KenT2** [comment]
I wondered how to get rid of all the loop around commits. I'll see if I can fine my HEAD.
I hate GIT ;-)

**Comment by nzjrs** [comment]
Yeah, it is a bit hard to learn ;-)


You should be able to just do a git rebase origin/master, or you can just
make a new branch for the pull request, and copy (or check out from your
old branch) the relevant changed files.

Then you can git add -p the relevant bits, and make a nice one-commit per
feature commit series.

**Comment by KenT2** [comment]
Tried that and failed so I have emailed the files to Davide.

**Pull request closed without merging**
