### PR TITLE
Improve reliability of server

### PR DESCRIPTION
**Pull request by nzjrs**
This improves the reliability of remi over unreliable networks considerably and fixes a nasty bug where one hung client freezes the server.

It also adds a fullscreen loading animation to ensure the websocket connection is working before allowing GUI interaction

### CODE REVIEW

**Comment by dddomodossola** [comment]
Hello John, have you already made tests with multiple clients?

**Comment by nzjrs** [comment]
Yes, I've been testing with 5 clients all day (Windows, linux, chrome,
Firefox, android)

**Comment by dddomodossola** [comment]
Do you have removed the commit for Input classes update suppression?

**Comment by nzjrs** [comment]
They were not really related to this pull request so I left them out. I'll
do another one for that

**Comment by dddomodossola** [comment]
Tested reasonably well. It works perfectly. Thank you!

**Pull request merged**
